export const states = [
    { value: 'UT', label: 'Utah' },
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' },
]

export const application_status = [
    { value: 'None', label: 'None', color: '' },
    { value: 'Interested', label: 'Interested', color: '#8C8C8C' },
    { value: 'Applied', label: 'Applied', color: '#6DA7D6' },
    { value: 'Phone Call', label: 'Phone Call', color: '#D567F5' },
    { value: 'Assignment', label: 'Assignment', color: '#ECB269' },
    { value: 'Interview', label: 'Interview', color: '#2A79DA' },
    { value: 'Offer', label: 'Offer', color: '#4BCE55' },
    { value: 'Accepted', label: 'Accepted', color: '#168000' },
    { value: 'Withdrawn', label: 'Withdrawn', color: '#666' },
    { value: 'Not Interested', label: 'Not Interested', color: '#BF5152' }
]

export const status_list = [
    { value: 'Interested', label: 'Interested', color: '#8C8C8C' },
    { value: 'Applied', label: 'Applied', color: '#6DA7D6' },
    { value: 'Phone Call', label: 'Phone Call', color: '#D567F5' },
    { value: 'Assignment', label: 'Assignment', color: '#ECB269' },
    { value: 'Interview', label: 'Interview', color: '#2A79DA' },
    { value: 'Offer', label: 'Offer', color: '#4BCE55' },
    { value: 'Accepted', label: 'Accepted', color: '#168000' },
    { value: 'Withdrawn', label: 'Withdrawn', color: '#666' },
    { value: 'Not Interested', label: 'Not Interested', color: '#BF5152' }
]

export const titles = [
    { value: 'Software Engineer Intern', label: 'Software Engineer Intern' },
    { value: 'Junior Software Engineer', label: 'Junior Software Engineer' },
    { value: 'Software Engineer', label: 'Software Engineer' },
    { value: 'Senior Software Engineer', label: 'Senior Software Engineer' },
    { value: 'Principal Software Engineer', label: 'Principal Software Engineer' },
    { value: 'Lead Engineer', label: 'Lead Engineer' },
    { value: 'CTO', label: 'CTO' },
    { value: 'QA Engineer', label: 'QA Engineer' },
    { value: 'Senior QA Engineer', label: 'Senior QA Engineer' },
    { value: 'Lead QA Engineer', label: 'Lead QA Engineer' },
    { value: 'Front End Developer', label: 'Front End Developer' },
    { value: 'Other', label: 'Other' },
]

export const cohorts = [
    { value: "Spring 2015", label: "Spring 2015" },
    { value: "Summer 2015", label: "Summer 2015" },
    { value: "Fall 2015", label: "Fall 2015" },
    { value: "Winter 2015", label: "Winter 2015" },
    { value: "Spring 2016", label: "Spring 2016" },
    { value: "Summer 2016", label: "Summer 2016" },
    { value: "Fall 2016", label: "Fall 2016" },
    { value: "Winter 2016", label: "Winter 2016" },
    { value: "Spring 2017", label: "Spring 2017" },
    { value: "Summer 2017", label: "Summer 2017" },
    { value: "Fall 2017", label: "Fall 2017" },
    { value: "Winter 2017", label: "Winter 2017" },
    { value: "Spring 2018", label: "Spring 2018" },
    { value: "Summer 2018", label: "Summer 2018" },
    { value: "Fall 2018", label: "Fall 2018" },
    { value: "Winter 2018", label: "Winter 2018" },
    { value: "Spring 2019", label: "Spring 2019" },
    { value: "Summer 2019", label: "Summer 2019" },
    { value: "Fall 2019", label: "Fall 2019" },
    { value: "Winter 2019", label: "Winter 2019" },
    { value: "Spring 2020", label: "Spring 2020" },
    { value: "Summer 2020", label: "Summer 2020" },
    { value: "Fall 2020", label: "Fall 2020" },
    { value: "Winter 2020", label: "Winter 2020" },
    { value: "Spring 2021", label: "Spring 2021" },
    { value: "Summer 2021", label: "Summer 2021" },
    { value: "Fall 2021", label: "Fall 2021" },
    { value: "Winter 2021", label: "Winter 2021" },
    { value: "Spring 2022", label: "Spring 2022" },
    { value: "Summer 2022", label: "Summer 2022" },
    { value: "Fall 2022", label: "Fall 2022" },
    { value: "Winter 2022", label: "Winter 2022" },
    { value: "Spring 2023", label: "Spring 2023" },
    { value: "Summer 2023", label: "Summer 2023" },
    { value: "Fall 2023", label: "Fall 2023" },
    { value: "Winter 2023", label: "Winter 2023" },
    { value: "Spring 2024", label: "Spring 2024" },
    { value: "Summer 2024", label: "Summer 2024" },
    { value: "Fall 2024", label: "Fall 2024" },
    { value: "Winter 2024", label: "Winter 2024" },
    { value: "Spring 2025", label: "Spring 2025" },
    { value: "Summer 2025", label: "Summer 2025" },
    { value: "Fall 2025", label: "Fall 2025" },
    { value: "Winter 2025", label: "Winter 2025" },
]


export default states;






